//
//  Localizable.h
//  TweakSettings
//
// Created by Dana Buehre on 5/22/21.
//

#ifndef LOCALIZABLE_H
#define LOCALIZABLE_H

#define RESPRING_APPLICATION_TITLE @"RESPRING_APPLICATION_TITLE"
#define SAFEMODE_APPLICATION_TITLE @"SAFEMODE_APPLICATION_TITLE"
#define UICACHE_APPLICATION_TITLE @"UICACHE_APPLICATION_TITLE"

#define ROOT_NAVIGATION_TITLE @"ROOT_NAVIGATION_TITLE"

#endif //LOCALIZABLE_H
