include $(THEOS)/makefiles/common.mk

PREFIX = $(THEOS)/toolchains/xcode11.xctoolchain/usr/bin/
TOOL_NAME = tweaksettings-utility

tweaksettings-utility_FILES = main.c
TARGET_CODESIGN_FLAGS = "-Sentitlements.plist"

include $(THEOS_MAKE_PATH)/tool.mk