//
//  Localizable.h
//  TweakSettings
//
// Created by Dana Buehre on 5/22/21.
//

#ifndef LOCALIZABLE_H
#define LOCALIZABLE_H

#define RESPRING_TITLE_KEY @"RESPRING_TITLE_KEY"
#define SAFEMODE_TITLE_KEY @"SAFEMODE_TITLE_KEY"
#define UICACHE_TITLE_KEY @"UICACHE_TITLE_KEY"
#define LDRESTART_TITLE_KEY @"LDRESTART_TITLE_KEY"
#define REBOOT_TITLE_KEY @"REBOOT_TITLE_KEY"
#define USREBOOT_TITLE_KEY @"USREBOOT_TITLE_KEY"
#define TWEAKINJECT_TITLE_KEY @"TWEAKINJECT_TITLE_KEY"

#define TWEAKINJECT_SUBTITLE_KEY @"TWEAKINJECT_SUBTITLE_KEY"
#define UICACHE_SUBTITLE_KEY @"UICACHE_SUBTITLE_KEY"
#define SAFEMODE_SUBTITLE_KEY @"SAFEMODE_SUBTITLE_KEY"
#define RESPRING_SUBTITLE_KEY @"RESPRING_SUBTITLE_KEY"
#define LDRESTART_SUBTITLE_KEY @"LDRESTART_SUBTITLE_KEY"
#define REBOOT_SUBTITLE_KEY @"REBOOT_SUBTITLE_KEY"
#define USREBOOT_SUBTITLE_KEY @"USREBOOT_SUBTITLE_KEY"

#define ROOT_NAVIGATION_TITLE_KEY @"ROOT_NAVIGATION_TITLE_KEY"
#define ROOT_NAVIGATION_RIGHT_TITLE_KEY @"ROOT_NAVIGATION_RIGHT_TITLE_KEY"
#define ROOT_NAVIGATION_LEFT_TITLE_KEY @"ROOT_NAVIGATION_LEFT_TITLE_KEY"

#define ALERT_CANCEL_TITLE_KEY @"ALERT_CANCEL_TITLE_KEY"
#define ALERT_DISMISS_TITLE_KEY @"ALERT_DISMISS_TITLE_KEY"
#define ALERT_ACTION_MESSAGE_KEY @"ALERT_ACTION_MESSAGE_KEY"

#define ALWAYS_SHOW_SEARCH_BAR_NAME_KEY @"ALWAYS_SHOW_SEARCH_BAR_NAME_KEY"
#define ALWAYS_SHOW_SEARCH_BAR_GROUP_KEY @"ALWAYS_SHOW_SEARCH_BAR_GROUP_KEY"
#define REQUIRE_ACTION_CONFIRMATION_NAME_KEY @"REQUIRE_ACTION_CONFIRMATION_NAME_KEY"
#define REQUIRE_ACTION_CONFIRMATION_GROUP_KEY @"REQUIRE_ACTION_CONFIRMATION_GROUP_KEY"
#define LONG_PRESS_OPENS_SETTINGS_NAME_KEY @"LONG_PRESS_OPENS_SETTINGS_NAME_KEY"
#define LONG_PRESS_OPENS_SETTINGS_GROUP_KEY @"LONG_PRESS_OPENS_SETTINGS_GROUP_KEY"
#define USE_LARGE_TITLES_ON_ROOT_LIST_NAME_KEY @"USE_LARGE_TITLES_ON_ROOT_LIST_NAME_KEY"
#define USE_LARGE_TITLES_ON_ROOT_LIST_GROUP_KEY @"USE_LARGE_TITLES_ON_ROOT_LIST_GROUP_KEY"
#define APP_SETTINGS_TITLE_NAME_KEY @"APP_SETTINGS_TITLE_NAME_KEY"
#define SOURCE_CODE_NAME_KEY @"SOURCE_CODE_NAME_KEY"
#define APP_VERSION_NAME_KEY @"APP_VERSION_NAME_KEY"

#define CHECK_FOR_UPDATES_TITLE_KEY @"CHECK_FOR_UPDATES_TITLE_KEY"
#define CHECK_FOR_UPDATES_ERROR_MESSAGE_KEY @"CHECK_FOR_UPDATES_ERROR_MESSAGE_KEY"
#define CHECK_FOR_UPDATES_PASS_MESSAGE_KEY @"CHECK_FOR_UPDATES_PASS_MESSAGE_KEY"
#define CHECK_FOR_UPDATES_FAIL_MESSAGE_KEY @"CHECK_FOR_UPDATES_FAIL_MESSAGE_KEY"

#endif //LOCALIZABLE_H
