#!/bin/sh

chown root:wheel /Applications/TweakSettings.app/TweakSettings
chmod 6755 /Applications/TweakSettings.app/TweakSettings
chmod +s /Applications/TweakSettings.app/TweakSettings

uicache -p /Applications/TweakSettings.app

exit 0;
