#!/bin/sh

chown root:wheel /usr/bin/tweaksettings-utility
chmod 0777 /usr/bin/tweaksettings-utility
chmod +s /usr/bin/tweaksettings-utility

chown root:wheel /Applications/TweakSettings.app/TweakSettings
chmod 0755 /Applications/TweakSettings.app/TweakSettings

uicache -p /Applications/TweakSettings.app

exit 0;
